# Autogenerated on 2012/10/10
# http://hackage.haskell.org/package/package-o-tron

$(BUILD)/Distribution/Pot/HaskellSourceParser.o : src/Distribution/Pot/HaskellSourceParser.lhs \
            $(BUILD)/Distribution/Pot/Types.hi
	-mkdir -p $(BUILD)/Distribution/Pot/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package attoparsec \
            -package base \
            -package filepath \
            -package text \
            -c $< -o $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            -i$(BUILD)/

$(BUILD)/Distribution/Pot/Modules.o : src/Distribution/Pot/Modules.lhs \
            $(BUILD)/Distribution/Pot/Packages.hi
	-mkdir -p $(BUILD)/Distribution/Pot/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package filemanip \
            -package filepath \
            -c $< -o $(BUILD)/Distribution/Pot/Modules.o \
            -i$(BUILD)/

$(BUILD)/Distribution/Pot/Packages.o : src/Distribution/Pot/Packages.lhs \
            $(BUILD)/Distribution/Pot/Types.hi
	-mkdir -p $(BUILD)/Distribution/Pot/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package process \
            -c $< -o $(BUILD)/Distribution/Pot/Packages.o \
            -i$(BUILD)/

$(BUILD)/Distribution/Pot/Parser.o : src/Distribution/Pot/Parser.lhs
	-mkdir -p $(BUILD)/Distribution/Pot/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -c $< -o $(BUILD)/Distribution/Pot/Parser.o \
            -i$(BUILD)/

$(BUILD)/Distribution/Pot/RecursiveGetSources.o : src/Distribution/Pot/RecursiveGetSources.lhs \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.hi \
            $(BUILD)/Distribution/Pot/Types.hi \
            $(BUILD)/Distribution/Pot/Packages.hi
	-mkdir -p $(BUILD)/Distribution/Pot/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package directory \
            -package filepath \
            -package mtl \
            -package text \
            -c $< -o $(BUILD)/Distribution/Pot/RecursiveGetSources.o \
            -i$(BUILD)/

$(BUILD)/Distribution/Pot/Types.o : src/Distribution/Pot/Types.lhs
	-mkdir -p $(BUILD)/Distribution/Pot/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package text \
            -c $< -o $(BUILD)/Distribution/Pot/Types.o \
            -i$(BUILD)/

$(BUILD)/CabalLint.o : tools/CabalLint.lhs \
            $(BUILD)/Distribution/Pot/Modules.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package Cabal \
            -package base \
            -package filepath \
            -package packdeps \
            -c $< -o $(BUILD)/CabalLint.o \
            -i$(BUILD)/

$(BUILD)/Dump.o : tools/Dump.lhs \
            $(BUILD)/Distribution/Pot/Modules.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -c $< -o $(BUILD)/Dump.o \
            -i$(BUILD)/

$(BUILD)/Dump2.o : tools/Dump2.lhs \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package groom \
            -c $< -o $(BUILD)/Dump2.o \
            -i$(BUILD)/

$(BUILD)/DumpPackageDB.o : tools/DumpPackageDB.lhs \
            $(BUILD)/Distribution/Pot/Packages.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -c $< -o $(BUILD)/DumpPackageDB.o \
            -i$(BUILD)/

$(BUILD)/MakeHaskellMake.o : tools/MakeHaskellMake.lhs \
            $(BUILD)/Distribution/Pot/Modules.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package filepath \
            -package time \
            -c $< -o $(BUILD)/MakeHaskellMake.o \
            -i$(BUILD)/

$(BUILD)/ShowPackages.o : tools/ShowPackages.lhs \
            $(BUILD)/Distribution/Pot/Modules.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -c $< -o $(BUILD)/ShowPackages.o \
            -i$(BUILD)/

$(BUILD)/TextHaskellSourceParser.o : tools/TextHaskellSourceParser.lhs \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package groom \
            -package text \
            -c $< -o $(BUILD)/TextHaskellSourceParser.o \
            -i$(BUILD)/
$(BUILD)/MakeHaskellMake : $(BUILD)/MakeHaskellMake.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            $(BUILD)/Distribution/Pot/Types.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(MAKEHASKELLMAKE_EXTRA) \
            -o $(BUILD)/MakeHaskellMake \
            $(BUILD)/MakeHaskellMake.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            $(BUILD)/Distribution/Pot/Types.o \
            -hide-all-packages \
            -package base \
            -package filemanip \
            -package filepath \
            -package process \
            -package text \
            -package time

$(BUILD)/Dump : $(BUILD)/Dump.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            $(BUILD)/Distribution/Pot/Types.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(DUMP_EXTRA) \
            -o $(BUILD)/Dump \
            $(BUILD)/Dump.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            $(BUILD)/Distribution/Pot/Types.o \
            -hide-all-packages \
            -package base \
            -package filemanip \
            -package filepath \
            -package process \
            -package text

$(BUILD)/DumpPackageDB : $(BUILD)/DumpPackageDB.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            $(BUILD)/Distribution/Pot/Types.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(DUMPPACKAGEDB_EXTRA) \
            -o $(BUILD)/DumpPackageDB \
            $(BUILD)/DumpPackageDB.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            $(BUILD)/Distribution/Pot/Types.o \
            -hide-all-packages \
            -package base \
            -package process \
            -package text

$(BUILD)/ShowPackages : $(BUILD)/ShowPackages.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            $(BUILD)/Distribution/Pot/Types.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(SHOWPACKAGES_EXTRA) \
            -o $(BUILD)/ShowPackages \
            $(BUILD)/ShowPackages.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            $(BUILD)/Distribution/Pot/Types.o \
            -hide-all-packages \
            -package base \
            -package filemanip \
            -package filepath \
            -package process \
            -package text

$(BUILD)/CabalLint : $(BUILD)/CabalLint.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            $(BUILD)/Distribution/Pot/Types.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(CABALLINT_EXTRA) \
            -o $(BUILD)/CabalLint \
            $(BUILD)/CabalLint.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            $(BUILD)/Distribution/Pot/Types.o \
            -hide-all-packages \
            -package Cabal \
            -package base \
            -package filemanip \
            -package filepath \
            -package packdeps \
            -package process \
            -package text

$(BUILD)/TextHaskellSourceParser : $(BUILD)/TextHaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/Types.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(TEXTHASKELLSOURCEPARSER_EXTRA) \
            -o $(BUILD)/TextHaskellSourceParser \
            $(BUILD)/TextHaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/Types.o \
            -hide-all-packages \
            -package attoparsec \
            -package base \
            -package filepath \
            -package groom \
            -package text

$(BUILD)/Dump2 : $(BUILD)/Dump2.o \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.o \
            $(BUILD)/Distribution/Pot/Types.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(DUMP2_EXTRA) \
            -o $(BUILD)/Dump2 \
            $(BUILD)/Dump2.o \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.o \
            $(BUILD)/Distribution/Pot/Types.o \
            -hide-all-packages \
            -package attoparsec \
            -package base \
            -package directory \
            -package filepath \
            -package groom \
            -package mtl \
            -package process \
            -package text


%.hi : %.o
	@:
