# Autogenerated on 2012/10/8
# http://hackage.haskell.org/package/package-o-tron

$(BUILD)/Distribution/Pot/Modules.o : src/Distribution/Pot/Modules.lhs \
            $(BUILD)/Distribution/Pot/Packages.hi
	-mkdir -p $(BUILD)/Distribution/Pot/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package filemanip \
            -package filepath \
            -c $< -o $(BUILD)/Distribution/Pot/Modules.o \
            -i$(BUILD)/

$(BUILD)/Distribution/Pot/Packages.o : src/Distribution/Pot/Packages.lhs
	-mkdir -p $(BUILD)/Distribution/Pot/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package process \
            -c $< -o $(BUILD)/Distribution/Pot/Packages.o \
            -i$(BUILD)/

$(BUILD)/CabalLint.o : tools/CabalLint.lhs \
            $(BUILD)/Distribution/Pot/Modules.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package Cabal \
            -package base \
            -package filepath \
            -package packdeps \
            -c $< -o $(BUILD)/CabalLint.o \
            -i$(BUILD)/

$(BUILD)/Dump.o : tools/Dump.lhs \
            $(BUILD)/Distribution/Pot/Modules.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -c $< -o $(BUILD)/Dump.o \
            -i$(BUILD)/

$(BUILD)/DumpPackageDB.o : tools/DumpPackageDB.lhs \
            $(BUILD)/Distribution/Pot/Packages.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -c $< -o $(BUILD)/DumpPackageDB.o \
            -i$(BUILD)/

$(BUILD)/MakeHaskellMake.o : tools/MakeHaskellMake.lhs \
            $(BUILD)/Distribution/Pot/Modules.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package filepath \
            -package time \
            -c $< -o $(BUILD)/MakeHaskellMake.o \
            -i$(BUILD)/

$(BUILD)/ShowPackages.o : tools/ShowPackages.lhs \
            $(BUILD)/Distribution/Pot/Modules.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -c $< -o $(BUILD)/ShowPackages.o \
            -i$(BUILD)/
$(BUILD)/MakeHaskellMake : $(BUILD)/MakeHaskellMake.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(MAKEHASKELLMAKE_EXTRA) \
            -o $(BUILD)/MakeHaskellMake \
            $(BUILD)/MakeHaskellMake.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            -hide-all-packages \
            -package base \
            -package filemanip \
            -package filepath \
            -package process \
            -package time

$(BUILD)/Dump : $(BUILD)/Dump.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(DUMP_EXTRA) \
            -o $(BUILD)/Dump \
            $(BUILD)/Dump.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            -hide-all-packages \
            -package base \
            -package filemanip \
            -package filepath \
            -package process

$(BUILD)/DumpPackageDB : $(BUILD)/DumpPackageDB.o \
            $(BUILD)/Distribution/Pot/Packages.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(DUMPPACKAGEDB_EXTRA) \
            -o $(BUILD)/DumpPackageDB \
            $(BUILD)/DumpPackageDB.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            -hide-all-packages \
            -package base \
            -package process

$(BUILD)/ShowPackages : $(BUILD)/ShowPackages.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(SHOWPACKAGES_EXTRA) \
            -o $(BUILD)/ShowPackages \
            $(BUILD)/ShowPackages.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            -hide-all-packages \
            -package base \
            -package filemanip \
            -package filepath \
            -package process

$(BUILD)/CabalLint : $(BUILD)/CabalLint.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(CABALLINT_EXTRA) \
            -o $(BUILD)/CabalLint \
            $(BUILD)/CabalLint.o \
            $(BUILD)/Distribution/Pot/Modules.o \
            $(BUILD)/Distribution/Pot/Packages.o \
            -hide-all-packages \
            -package Cabal \
            -package base \
            -package filemanip \
            -package filepath \
            -package packdeps \
            -package process


%.hi : %.o
	@:
