# Autogenerated on 2012/10/12
# http://hackage.haskell.org/package/package-o-tron

$(BUILD)/SummarizeSources.o : tools/SummarizeSources.lhs \
            $(BUILD)/Distribution/Pot/InstalledPackages.hi \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package groom \
            -package split \
            -c $< -o $(BUILD)/SummarizeSources.o \
            -i$(BUILD)/

$(BUILD)/TestHaskellSourceParser.o : tools/TestHaskellSourceParser.lhs \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package groom \
            -package text \
            -c $< -o $(BUILD)/TestHaskellSourceParser.o \
            -i$(BUILD)/

$(BUILD)/SavePackages.o : tools/SavePackages.lhs \
            $(BUILD)/Distribution/Pot/DeepDependencies.hi \
            $(BUILD)/Distribution/Pot/InstalledPackages.hi \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.hi \
            $(BUILD)/Distribution/Pot/Types.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package directory \
            -package filemanip \
            -package filepath \
            -package process \
            -package split \
            -package text \
            -c $< -o $(BUILD)/SavePackages.o \
            -i$(BUILD)/

$(BUILD)/MakeHaskellMake.o : tools/MakeHaskellMake.lhs \
            $(BUILD)/Distribution/Pot/DeepDependencies.hi \
            $(BUILD)/Distribution/Pot/InstalledPackages.hi \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.hi \
            $(BUILD)/Distribution/Pot/Types.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package filepath \
            -package split \
            -package text \
            -package time \
            -c $< -o $(BUILD)/MakeHaskellMake.o \
            -i$(BUILD)/

$(BUILD)/CabalLint.o : tools/CabalLint.lhs \
            $(BUILD)/Distribution/Pot/DeepDependencies.hi \
            $(BUILD)/Distribution/Pot/InstalledPackages.hi \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.hi \
            $(BUILD)/Distribution/Pot/Types.hi
	-mkdir -p $(BUILD)/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package Cabal \
            -package base \
            -package directory \
            -package filepath \
            -package packdeps \
            -package text \
            -c $< -o $(BUILD)/CabalLint.o \
            -i$(BUILD)/

$(BUILD)/Distribution/Pot/DeepDependencies.o : src/Distribution/Pot/DeepDependencies.lhs \
            $(BUILD)/Distribution/Pot/Types.hi
	-mkdir -p $(BUILD)/Distribution/Pot/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -c $< -o $(BUILD)/Distribution/Pot/DeepDependencies.o \
            -i$(BUILD)/

$(BUILD)/Distribution/Pot/RecursiveGetSources.o : src/Distribution/Pot/RecursiveGetSources.lhs \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.hi \
            $(BUILD)/Distribution/Pot/InstalledPackages.hi \
            $(BUILD)/Distribution/Pot/Types.hi
	-mkdir -p $(BUILD)/Distribution/Pot/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package directory \
            -package filepath \
            -package mtl \
            -package text \
            -c $< -o $(BUILD)/Distribution/Pot/RecursiveGetSources.o \
            -i$(BUILD)/

$(BUILD)/Distribution/Pot/InstalledPackages.o : src/Distribution/Pot/InstalledPackages.lhs \
            $(BUILD)/Distribution/Pot/Types.hi
	-mkdir -p $(BUILD)/Distribution/Pot/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package Cabal \
            -package base \
            -package process \
            -package split \
            -package text \
            -c $< -o $(BUILD)/Distribution/Pot/InstalledPackages.o \
            -i$(BUILD)/

$(BUILD)/Distribution/Pot/HaskellSourceParser.o : src/Distribution/Pot/HaskellSourceParser.lhs \
            $(BUILD)/Distribution/Pot/Types.hi
	-mkdir -p $(BUILD)/Distribution/Pot/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package attoparsec \
            -package base \
            -package filepath \
            -package text \
            -c $< -o $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            -i$(BUILD)/

$(BUILD)/Distribution/Pot/Types.o : src/Distribution/Pot/Types.lhs
	-mkdir -p $(BUILD)/Distribution/Pot/
	$(HC) $(HC_OPTS) -hide-all-packages -outputdir $(BUILD)/  \
            -package base \
            -package text \
            -c $< -o $(BUILD)/Distribution/Pot/Types.o \
            -i$(BUILD)/
$(BUILD)/SummarizeSources : $(BUILD)/SummarizeSources.o \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/InstalledPackages.o \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.o \
            $(BUILD)/Distribution/Pot/Types.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(SUMMARIZESOURCES_EXTRA) \
            -o $(BUILD)/SummarizeSources \
            $(BUILD)/SummarizeSources.o \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/InstalledPackages.o \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.o \
            $(BUILD)/Distribution/Pot/Types.o \
            -package Cabal \
            -package attoparsec \
            -package base \
            -package directory \
            -package filepath \
            -package groom \
            -package mtl \
            -package process \
            -package split \
            -package text

$(BUILD)/TestHaskellSourceParser : $(BUILD)/TestHaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/Types.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(TESTHASKELLSOURCEPARSER_EXTRA) \
            -o $(BUILD)/TestHaskellSourceParser \
            $(BUILD)/TestHaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/Types.o \
            -package attoparsec \
            -package base \
            -package filepath \
            -package groom \
            -package text

$(BUILD)/SavePackages : $(BUILD)/SavePackages.o \
            $(BUILD)/Distribution/Pot/DeepDependencies.o \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/InstalledPackages.o \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.o \
            $(BUILD)/Distribution/Pot/Types.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(SAVEPACKAGES_EXTRA) \
            -o $(BUILD)/SavePackages \
            $(BUILD)/SavePackages.o \
            $(BUILD)/Distribution/Pot/DeepDependencies.o \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/InstalledPackages.o \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.o \
            $(BUILD)/Distribution/Pot/Types.o \
            -package Cabal \
            -package attoparsec \
            -package base \
            -package directory \
            -package filemanip \
            -package filepath \
            -package mtl \
            -package process \
            -package split \
            -package text

$(BUILD)/MakeHaskellMake : $(BUILD)/MakeHaskellMake.o \
            $(BUILD)/Distribution/Pot/DeepDependencies.o \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/InstalledPackages.o \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.o \
            $(BUILD)/Distribution/Pot/Types.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(MAKEHASKELLMAKE_EXTRA) \
            -o $(BUILD)/MakeHaskellMake \
            $(BUILD)/MakeHaskellMake.o \
            $(BUILD)/Distribution/Pot/DeepDependencies.o \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/InstalledPackages.o \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.o \
            $(BUILD)/Distribution/Pot/Types.o \
            -package Cabal \
            -package attoparsec \
            -package base \
            -package directory \
            -package filepath \
            -package mtl \
            -package process \
            -package split \
            -package text \
            -package time

$(BUILD)/CabalLint : $(BUILD)/CabalLint.o \
            $(BUILD)/Distribution/Pot/DeepDependencies.o \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/InstalledPackages.o \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.o \
            $(BUILD)/Distribution/Pot/Types.o
	-mkdir -p $(BUILD)/
	$(HL) $(HL_OPTS) $(CABALLINT_EXTRA) \
            -o $(BUILD)/CabalLint \
            $(BUILD)/CabalLint.o \
            $(BUILD)/Distribution/Pot/DeepDependencies.o \
            $(BUILD)/Distribution/Pot/HaskellSourceParser.o \
            $(BUILD)/Distribution/Pot/InstalledPackages.o \
            $(BUILD)/Distribution/Pot/RecursiveGetSources.o \
            $(BUILD)/Distribution/Pot/Types.o \
            -package Cabal \
            -package attoparsec \
            -package base \
            -package directory \
            -package filepath \
            -package mtl \
            -package packdeps \
            -package process \
            -package split \
            -package text


%.hi : %.o
	@:
