Example of calling this file:

MakeHaskellMake --hide-package package-o-tron --hide-package haskell2010 --hide-package haskell98 -isrc:tools tools/*.lhs

It will generate rules to compile all the .o files and link the exes,
with explicit package lists.

See the included Makefile, autorules.mk file for an example of how to
use this, and an example of what is output.


> {-# LANGUAGE OverloadedStrings,TupleSections #-}
> import Distribution.Pot.MakefileGen
> import Data.List
> import System.Environment
> import Data.Time.Clock
> import Data.Time.Calendar
> import Data.List.Split
> import qualified Data.Text as T

> data Opts =
>     Opts
>     {srcFolders :: [FilePath]
>     ,hidePackages :: [T.Text]
>     ,roots :: [FilePath]
>     ,packageDB :: Maybe FilePath
>     } deriving Show

> main :: IO ()
> main = do
>   opts <- parseArgs `fmap` getArgs
>   --pkgs <- readPackages
>   mfg <- makefileGen (packageDB opts) (srcFolders opts) (roots opts) (hidePackages opts)
>   -- write small note
>   (y,m,d) <- (toGregorian . utctDay) `fmap` getCurrentTime
>   putStrLn $ "# Autogenerated on " ++ show y ++ "/" ++ show m ++ "/" ++ show d ++ "\n\
>              \# http://hackage.haskell.org/package/package-o-tron\n"
>   putStrLn $ ppMakefile mfg

> parseArgs :: [String] -> Opts
> parseArgs = f [] [] [] Nothing
>   where
>     f is ps rs pdb (x:xs) | "-i" `isPrefixOf` x =
>         let is' = splitOn ":" $ drop 2 x
>         in f (is ++ is') ps rs pdb xs
>     f is ps rs pdb ("--hide-package":p:xs) =
>         f is (p:ps) rs pdb xs
>     f is ps rs pdb ("--package-db":p:xs) =
>         f is ps rs (Just p) xs
>     f  _is _ps _rs _pdb (["--hide-package"]) =
>         error "no package name after --hide-package"
>     f is ps rs pdb (x:xs) =
>         f is ps (x:rs) pdb xs
>     f is ps rs pdb [] =
>         Opts is (map T.pack ps) rs pdb

